spring.application.name=addressbookapp

server.port=8080

# DB
spring.datasource.url=jdbc:mysql://localhost:3306/addressbook_db_springboo
spring.datasource.username=root
spring.datasource.password=barnam@555

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true